namespace: monitoring

grafana:
  replicas: 1
  image:
    repository: grafana/grafana
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 32000
  ingress:
    enabled: false
  resources: {}

prometheusOperator:
  replicas: 1
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 9090
    nodePort: 32001
  resources: {}

kubeStateMetrics:
  replicas: 1
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 32002
  resources: {}

alertmanager:
  enabled: true
  replicas: 1
  image:
    repository: quay.io/prometheus/alertmanager
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 9093
    nodePort: 32003
  resources: {}

nodeExporter:
  enabled: true
  replicas: 1
  image:
    repository: quay.io/prometheus/node-exporter
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 9100
    nodePort: 32004
  resources: {}

tolerations: []
affinity: {}
